[2024-11-28T10:00:11.411+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T10:00:11.428+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.save_data scheduled__2024-11-28T09:30:00+00:00 [queued]>
[2024-11-28T10:00:11.438+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.save_data scheduled__2024-11-28T09:30:00+00:00 [queued]>
[2024-11-28T10:00:11.438+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-11-28T10:00:11.451+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): save_data> on 2024-11-28 09:30:00+00:00
[2024-11-28T10:00:11.463+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=675) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-28T10:00:11.464+0000] {standard_task_runner.py:72} INFO - Started process 701 to run task
[2024-11-28T10:00:11.465+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_atropelamento', 'save_data', 'scheduled__2024-11-28T09:30:00+00:00', '--job-id', '1803', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmpdp95u0of']
[2024-11-28T10:00:11.466+0000] {standard_task_runner.py:105} INFO - Job 1803: Subtask save_data
[2024-11-28T10:00:11.523+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_atropelamento.save_data scheduled__2024-11-28T09:30:00+00:00 [running]> on host 3de0f1e46a39
[2024-11-28T10:00:11.652+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_atropelamento' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T09:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T09:30:00+00:00'
[2024-11-28T10:00:11.653+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-28T10:00:11.654+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-28T10:00:11.654+0000] {logging_mixin.py:190} INFO - Current task name:save_data state:running start_date:2024-11-28 10:00:11.429247+00:00
[2024-11-28T10:00:11.655+0000] {logging_mixin.py:190} INFO - Dag name:get_inaturalist_data_atropelamento and current dag run status:running
[2024-11-28T10:00:11.655+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T10:00:11.655+0000] {inaturalist_dag.py:197} INFO - No new observations to store.
[2024-11-28T10:00:11.656+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-28T10:00:11.664+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T10:00:11.665+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=get_inaturalist_data_atropelamento, task_id=save_data, run_id=scheduled__2024-11-28T09:30:00+00:00, execution_date=20241128T093000, start_date=20241128T100011, end_date=20241128T100011
[2024-11-28T10:00:11.677+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-28T10:00:11.678+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-28T10:00:11.678+0000] {logging_mixin.py:190} INFO - Dag name:get_inaturalist_data_atropelamento queued_at:2024-11-28 10:00:00.447846+00:00
[2024-11-28T10:00:11.678+0000] {logging_mixin.py:190} INFO - Task hostname:3de0f1e46a39 operator:_PythonDecoratedOperator
[2024-11-28T10:00:11.721+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-28T10:00:11.737+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T10:00:11.739+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
