[2024-11-19T10:59:38.892+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T10:59:38.953+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_gbif_data_atropelamento.get_all_data manual__2024-11-19T10:58:26.429641+00:00 [queued]>
[2024-11-19T10:59:38.987+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_gbif_data_atropelamento.get_all_data manual__2024-11-19T10:58:26.429641+00:00 [queued]>
[2024-11-19T10:59:38.988+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2024-11-19T10:59:39.042+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_all_data> on 2024-11-19 10:58:26.429641+00:00
[2024-11-19T10:59:39.081+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-19T10:59:39.089+0000] {standard_task_runner.py:72} INFO - Started process 284 to run task
[2024-11-19T10:59:39.097+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_gbif_data_atropelamento', 'get_all_data', 'manual__2024-11-19T10:58:26.429641+00:00', '--job-id', '706', '--raw', '--subdir', 'DAGS_FOLDER/gbif_dag.py', '--cfg-path', '/tmp/tmpmunk2suz']
[2024-11-19T10:59:39.101+0000] {standard_task_runner.py:105} INFO - Job 706: Subtask get_all_data
[2024-11-19T10:59:39.276+0000] {task_command.py:467} INFO - Running <TaskInstance: get_gbif_data_atropelamento.get_all_data manual__2024-11-19T10:58:26.429641+00:00 [running]> on host 1bd5b698e8d7
[2024-11-19T10:59:39.594+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_gbif_data_atropelamento' AIRFLOW_CTX_TASK_ID='get_all_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T10:58:26.429641+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T10:58:26.429641+00:00'
[2024-11-19T10:59:39.603+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-19T10:59:39.604+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-19T10:59:39.604+0000] {logging_mixin.py:190} INFO - Current task name:get_all_data state:running start_date:2024-11-19 10:59:38.954365+00:00
[2024-11-19T10:59:39.605+0000] {logging_mixin.py:190} INFO - Dag name:get_gbif_data_atropelamento and current dag run status:running
[2024-11-19T10:59:39.605+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T10:59:39.606+0000] {gbif_dag.py:220} INFO - Getting data from keyword: atropelamento
[2024-11-19T10:59:40.002+0000] {logging_mixin.py:190} INFO - each occurrence {'key': 1324007419, 'datasetKey': '45a34757-f7fa-4989-a9fc-e98629361c43', 'publishingOrgKey': '667644b9-7b93-4892-80c7-c4271735c515', 'networkKeys': ['99d66b6c-9087-452f-a9d4-f15f2c2d0e7e'], 'installationKey': 'b38ff2b7-c8af-454e-b5af-ee760f0d5bca', 'hostingOrganizationKey': '8595cd50-87c0-11dc-bb35-b8a03c50a862', 'publishingCountry': 'BR', 'protocol': 'EML', 'lastCrawled': '2024-11-14T13:13:12.541+00:00', 'lastParsed': '2024-11-14T13:14:10.159+00:00', 'crawlId': 451, 'extensions': {}, 'basisOfRecord': 'PRESERVED_SPECIMEN', 'occurrenceStatus': 'PRESENT', 'taxonKey': 2481006, 'kingdomKey': 1, 'phylumKey': 44, 'classKey': 212, 'orderKey': 7191407, 'familyKey': 5240, 'genusKey': 2480996, 'speciesKey': 2481006, 'acceptedTaxonKey': 2481006, 'scientificName': 'Falco femoralis Temminck, 1822', 'acceptedScientificName': 'Falco femoralis Temminck, 1822', 'kingdom': 'Animalia', 'phylum': 'Chordata', 'order': 'Falconiformes', 'family': 'Falconidae', 'genus': 'Falco', 'species': 'Falco femoralis', 'genericName': 'Falco', 'specificEpithet': 'femoralis', 'taxonRank': 'SPECIES', 'taxonomicStatus': 'ACCEPTED', 'iucnRedListCategory': 'LC', 'continent': 'SOUTH_AMERICA', 'stateProvince': 'Espírito Santo', 'gadm': {}, 'issues': ['CONTINENT_DERIVED_FROM_COUNTRY', 'INSTITUTION_MATCH_NONE'], 'modified': '2019-10-03T11:20:42.000+00:00', 'lastInterpreted': '2024-11-14T13:14:10.159+00:00', 'references': 'https://specieslink.net/guid/112/7668', 'license': 'http://creativecommons.org/licenses/by/4.0/legalcode', 'isSequenced': False, 'identifiers': [{'identifier': 'https://specieslink.net/guid/112/7668'}], 'media': [], 'facts': [], 'relations': [], 'isInCluster': False, 'recordedBy': 'A.M. Gouvea', 'class': 'Aves', 'countryCode': 'BR', 'recordedByIDs': [], 'identifiedByIDs': [], 'gbifRegion': 'LATIN_AMERICA', 'country': 'Brazil', 'publishedByGbifRegion': 'LATIN_AMERICA', 'rightsHolder': 'Coleção de Aves MBML', 'identifier': 'https://specieslink.net/guid/112/7668', 'catalogNumber': '7668', 'institutionCode': 'INMA', 'locality': "Aeroporto 'Eurico Salles Aguiar', Vitória, ES", 'municipality': 'Vitória', 'ownerInstitutionCode': 'Instituto Nacional da Mata Atlântica', 'gbifID': '1324007419', 'collectionCode': 'MBML-AVES', 'occurrenceRemarks': 'Pele danificada devido morte por atropelamento.', 'occurrenceID': 'https://specieslink.net/guid/112/7668', 'collectionID': 'https://specieslink.net/col/112', '_datasetKey': {'title': 'MBML-Aves - Coleção de Aves MBML'}, '_publishingOrgKey': {'title': 'Instituto Nacional da Mata Atlântica'}, '_verbatimRecord': {'http://rs.tdwg.org/dwc/terms/scientificName': 'Falco femoralis'}}
[2024-11-19T10:59:40.004+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gbif_dag.py", line 223, in get_all_data
    offset = int(Variable.get(f"gbif_{keyword}_offset", default_var=0))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gbif_dag.py", line 123, in get_data
    publishing_org_key = each_occurrence.get('publishingOrgKey') # .get('title')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
[2024-11-19T10:59:40.067+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-19T10:59:40.068+0000] {logging_mixin.py:190} INFO - Task start:2024-11-19 10:59:38.954365+00:00 end:2024-11-19 10:59:40.067129+00:00 duration:1.112764
[2024-11-19T10:59:40.069+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): get_all_data> dag:<DAG: get_gbif_data_atropelamento> dagrun:<DagRun get_gbif_data_atropelamento @ 2024-11-19 10:58:26.429641+00:00: manual__2024-11-19T10:58:26.429641+00:00, state:running, queued_at: 2024-11-19 10:58:26.444521+00:00. externally triggered: True>
[2024-11-19T10:59:40.069+0000] {logging_mixin.py:190} INFO - Failure caused by 'str' object has no attribute 'get'
[2024-11-19T10:59:40.078+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=get_gbif_data_atropelamento, task_id=get_all_data, run_id=manual__2024-11-19T10:58:26.429641+00:00, execution_date=20241119T105826, start_date=20241119T105938, end_date=20241119T105940
[2024-11-19T10:59:40.132+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T10:59:40.133+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 706 for task get_all_data ('str' object has no attribute 'get'; 284)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gbif_dag.py", line 223, in get_all_data
    offset = int(Variable.get(f"gbif_{keyword}_offset", default_var=0))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gbif_dag.py", line 123, in get_data
    publishing_org_key = each_occurrence.get('publishingOrgKey') # .get('title')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
[2024-11-19T10:59:40.217+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-19T10:59:40.320+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-19T10:59:40.326+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
